# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"

mod "apt",
   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "chromedriver",
   :git => "git://github.com/laurentmoss/puppet-chromedriver.git"

mod "firefox",
   :git => "git://github.com/runthebusiness/puppet-firefox.git"

mod "nanliu/staging"
